import { Box, Heading } from "@chakra-ui/react";

import Head from "next/head";
import type { NextPage } from "next";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from BugTracker" }]);

  return (
    <>
      <Head>
        <title>Bug tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box py="8" px="5">
        <Heading size="md" mb="4 ">
          Projects
        </Heading>

        <div className="mt-4">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
      </Box>
    </>
  );
};

export default Home;
