import { Box, HStack } from "@chakra-ui/react";
import React, { ReactNode } from "react";

import Footer from "../components/footer/footer";
import Head from "next/head";
import Sidebar from "../components/sidebar/sidebar";

type Props = {
  children: ReactNode;
};

const Dashboard = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Mothlight</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HStack pl="200px" gap="0">
        <Sidebar />
        <Box
          flexGrow={1}
          width="100%"
          ml="0"
          minHeight="100vh"
          display="flex"
          flexDir="column"
        >
          <main className="flex-grow">{children}</main>
          <Footer />
        </Box>
      </HStack>
    </>
  );
};

export default Dashboard;
